# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\source\code\pyqt\mycode\chapter01\imgshow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(634, 597)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(50, 80, 101, 461))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.openbtn = QtWidgets.QPushButton(self.groupBox)
        self.openbtn.setGeometry(QtCore.QRect(10, 30, 75, 23))
        self.openbtn.setObjectName("openbtn")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(220, 20, 161, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(160, 80, 431, 471))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.img_pre = QtWidgets.QLabel(self.groupBox_2)
        self.img_pre.setGeometry(QtCore.QRect(10, 10, 421, 211))
        self.img_pre.setText("")
        self.img_pre.setObjectName("img_pre")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.openbtn.setText(_translate("Form", "打开"))
        self.label.setText(_translate("Form", "图像显示"))
