# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\source\code\coding\pyqt5\pyqt5_yolov5_detect\ui\detect_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1033, 608)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 391, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.vl_pre = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.vl_pre.setContentsMargins(0, 0, 0, 0)
        self.vl_pre.setObjectName("vl_pre")
        self.q_pre = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.q_pre.setText("")
        self.q_pre.setObjectName("q_pre")
        self.vl_pre.addWidget(self.q_pre)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(850, 20, 160, 511))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.vl_c = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vl_c.setContentsMargins(0, 0, 0, 0)
        self.vl_c.setObjectName("vl_c")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.btn_run = QtWidgets.QPushButton(self.groupBox)
        self.btn_run.setGeometry(QtCore.QRect(40, 370, 75, 61))
        self.btn_run.setObjectName("btn_run")
        self.btn_video = QtWidgets.QPushButton(self.groupBox)
        self.btn_video.setGeometry(QtCore.QRect(40, 260, 75, 23))
        self.btn_video.setObjectName("btn_video")
        self.btn_img = QtWidgets.QPushButton(self.groupBox)
        self.btn_img.setGeometry(QtCore.QRect(40, 180, 75, 23))
        self.btn_img.setObjectName("btn_img")
        self.btn_weight = QtWidgets.QPushButton(self.groupBox)
        self.btn_weight.setGeometry(QtCore.QRect(40, 50, 75, 23))
        self.btn_weight.setObjectName("btn_weight")
        self.btn_cls = QtWidgets.QPushButton(self.groupBox)
        self.btn_cls.setGeometry(QtCore.QRect(40, 110, 75, 23))
        self.btn_cls.setObjectName("btn_cls")
        self.vl_c.addWidget(self.groupBox)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(420, 20, 421, 511))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.vl_res = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.vl_res.setContentsMargins(0, 0, 0, 0)
        self.vl_res.setObjectName("vl_res")
        self.q_res = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.q_res.setText("")
        self.q_res.setObjectName("q_res")
        self.vl_res.addWidget(self.q_res)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(630, 540, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 540, 54, 12))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1033, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyQt5+YOLOv5示例"))
        self.btn_run.setText(_translate("MainWindow", "检测"))
        self.btn_video.setText(_translate("MainWindow", "选择视频"))
        self.btn_img.setText(_translate("MainWindow", "选择图片"))
        self.btn_weight.setText(_translate("MainWindow", "选择权重"))
        self.btn_cls.setText(_translate("MainWindow", "类别文件"))
        self.label.setText(_translate("MainWindow", "检测结果"))
        self.label_2.setText(_translate("MainWindow", "原图"))
