# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\source\code\coding\pyqt5\pyqt5_yolov5_detect\ui\login_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login_win(object):
    def setupUi(self, Login_win):
        Login_win.setObjectName("Login_win")
        Login_win.resize(1033, 600)
        self.centralwidget = QtWidgets.QWidget(Login_win)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(460, 330, 75, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.btn_login.setFont(font)
        self.btn_login.setObjectName("btn_login")
        self.bg_img_label = QtWidgets.QLabel(self.centralwidget)
        self.bg_img_label.setGeometry(QtCore.QRect(-1, -1, 1051, 571))
        self.bg_img_label.setText("")
        self.bg_img_label.setObjectName("bg_img_label")
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(460, 400, 75, 24))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.btn_exit.setFont(font)
        self.btn_exit.setObjectName("btn_exit")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(270, 90, 571, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(24)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.bg_img_label.raise_()
        self.btn_login.raise_()
        self.btn_exit.raise_()
        self.title_label.raise_()
        Login_win.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Login_win)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1033, 23))
        self.menubar.setObjectName("menubar")
        Login_win.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Login_win)
        self.statusbar.setObjectName("statusbar")
        Login_win.setStatusBar(self.statusbar)

        self.retranslateUi(Login_win)
        QtCore.QMetaObject.connectSlotsByName(Login_win)

    def retranslateUi(self, Login_win):
        _translate = QtCore.QCoreApplication.translate
        Login_win.setWindowTitle(_translate("Login_win", "YOLOv5识别检测系统"))
        self.btn_login.setText(_translate("Login_win", "进入系统"))
        self.btn_exit.setText(_translate("Login_win", "退出系统"))
        self.title_label.setText(_translate("Login_win", "                   检测系统"))
